/** FilterBuilder's built in copy. */
export const strings = {
  label: 'Filters',
  where: 'Where',
  conjunctions: { and: 'and', or: 'or' },
  conjunction: 'Match',
  condition: (index: number) => `Filter ${String(index)}`,
  group: (index: number) => `Filter group ${String(index)}`,
  addFilter: 'Add filter',
  addGroup: 'Add filter group',
  removeFilter: 'Remove filter',
  removeGroup: 'Remove filter group',
  attributes: 'Attributes',
  searchAttributes: 'Search attributes',
  chooseAttribute: 'Choose an attribute',
  /** How a path through relations reads on the attribute button: Company › Country. */
  pathJoin: ' › ',
  operators: 'Operators',
  value: (name: string) => `${name} value`,
  from: (name: string) => `${name} from`,
  to: (name: string) => `${name} to`,
  between: 'and',
  range: (name: string) => `${name} range`,
  chooseRange: 'Choose a range',
  ranges: {
    today: 'today',
    this_week: 'this week',
    this_month: 'this month',
    last_month: 'last month',
  },
  amount: (name: string) => `${name}, how many`,
  unit: (name: string) => `${name}, days, weeks, months or years`,
  units: { day: 'days', week: 'weeks', month: 'months', year: 'years' },
  noFilters: 'No filters yet',
  noFiltersText: 'Add a filter to narrow this view.',
} as const;
