// The component library's public surface: what screens import from '@crm/ui'.
// The theme logic stays on its own subpath, '@crm/ui/theme', so the boot script
// test and other tools can load it without React. Workbench pieces (Stage,
// StoryRoot) and the provider's hooks stay inside the library.
import { describe, expect, it } from 'vitest';
import * as ui from './index.ts';

describe('@crm/ui', () => {
  it('exports the data hues', () => {
    expect(ui.HUES).toEqual(['gray', 'red', 'orange', 'yellow', 'lime', 'green', 'sky', 'blue', 'purple']);
  });

  it('exports exactly the components, the provider, the toast factory and the shared helpers', () => {
    expect(Object.keys(ui).sort()).toEqual([
      'AppShell',
      'AppShellContext',
      'AttributeDisplay',
      'AttributeEditor',
      'Avatar',
      'AvatarStack',
      'Badge',
      'Breadcrumbs',
      'Button',
      'Callout',
      'Card',
      'Checkbox',
      'Code',
      'CodeInput',
      'ContextMenu',
      'CopyButton',
      'Currency',
      'DatePicker',
      'DateRangePicker',
      'DescriptionList',
      'Disclosure',
      'DisclosureGroup',
      'EmptyState',
      'FIELD_TYPES',
      'Field',
      'FileDrop',
      'FileIcon',
      'FileItem',
      'FilterChip',
      'HUES',
      'HuePicker',
      'Icon',
      'IconPicker',
      'Kbd',
      'LOADING_TIMING',
      'Link',
      'LinkChip',
      'Mention',
      'Menu',
      'MenuItem',
      'MenuSection',
      'MenuSeparator',
      'MenuTrigger',
      'Meter',
      'Modal',
      'ModalTrigger',
      'NavItem',
      'NavSection',
      'Panel',
      'Path',
      'Popover',
      'ProgressBar',
      'Radio',
      'RadioGroup',
      'Rating',
      'RecordChip',
      'RelativeTime',
      'RemoteCursor',
      'SegmentedControl',
      'Select',
      'Separator',
      'ShortcutHelp',
      'Sidebar',
      'Skeleton',
      'SortChip',
      'Spinner',
      'SplitButton',
      'StatusDot',
      'Steps',
      'SubmenuTrigger',
      'Switch',
      'TabPanel',
      'Table',
      'Tabs',
      'Tag',
      'TagList',
      'ThemeSwitch',
      'ToggleButton',
      'Toolbar',
      'Tooltip',
      'TopBar',
      'TruncatedText',
      'UiProvider',
      'Variable',
      'ViewBar',
      'VisuallyHidden',
      'arraySource',
      'columnWidthOf',
      'createPhoneParser',
      'createToasts',
      'dayIn',
      'fieldTypeOf',
      'fileIconName',
      'formatFileSize',
      'isRefusal',
      'isSystemOnly',
      'loadPhoneLibrary',
      'quickPicks',
      'safeHref',
      'safeImageSrc',
      'useDelayedLoading',
    ]);
  });
});
