/** The field set's built in copy. */
export const strings = {
  /** Read by screen readers for an empty value; sight sees an empty cell or a dash. */
  empty: 'Empty',
  emptyMark: '—',
  required: (name: string) => `${name} is required.`,
  refused: (reason: string) => reason,
  readOnly: 'Read only',
  computed: 'Worked out by the system',
  system: 'Set by the system',
  ai: 'Filled by AI',
  refresh: 'Refresh',
  whereFrom: 'Where this came from',
  more: (count: number) => `+${String(count)}`,
  showMore: (count: number) => `Show ${String(count)} more`,
  add: (name: string) => `Add ${name}…`,
  remove: (label: string) => `Remove ${label}`,
  choose: (name: string) => `Choose ${name}…`,
  search: (name: string) => `Search ${name}`,
  addAnother: 'Add another',
  me: 'Me',
  unknown: 'Unknown',
  /** Operators, as a filter reads them. */
  operators: {
    is: 'is',
    is_not: 'is not',
    contains: 'contains',
    does_not_contain: 'does not contain',
    eq: '=',
    neq: '≠',
    gt: '>',
    gte: '≥',
    lt: '<',
    lte: '≤',
    between: 'is between',
    before: 'is before',
    after: 'is after',
    within: 'is within',
    within_last: 'is within the last',
    at_least: 'is at least',
    at_most: 'is at most',
    is_any_of: 'is any of',
    contains_any_of: 'contains any of',
    contains_all_of: 'contains all of',
    contains_none_of: 'contains none of',
    is_me: 'is me',
    is_empty: 'is empty',
    is_not_empty: 'is not empty',
    is_checked: 'is checked',
    is_not_checked: 'is not checked',
    has_files: 'has files',
    first_name_is: 'first name is',
    last_name_is: 'last name is',
    country_is: 'country is',
    locality_is: 'city is',
    region_is: 'region is',
    name_contains: 'name contains',
    kind_is: 'kind is',
    through: 'where',
  },
} as const;
