// The one place the app imports lucide-react. Every icon the app uses is listed
// here under its lucide.dev name, so only these ship and an unknown name is a
// type error. Add an icon with one import and one line. The curated object
// icons (OBJECT_ICONS in contracts) are all here too; a test checks it.
import {
  Activity,
  Apple,
  Archive,
  ArrowDownWideNarrow,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUpNarrowWide,
  ArrowUpRight,
  AtSign,
  Atom,
  Award,
  Baby,
  BadgeDollarSign,
  BadgePercent,
  Banknote,
  Bell,
  Bike,
  Bird,
  Blocks,
  BookOpen,
  Bookmark,
  Bot,
  Box,
  Braces,
  Brain,
  Briefcase,
  BriefcaseBusiness,
  Brush,
  Bug,
  Building,
  BuildingComplex,
  Cake,
  Calendar,
  CalendarClock,
  CalendarDays,
  Camera,
  Car,
  Castle,
  Cat,
  ChartBar,
  ChartLine,
  ChartPie,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Church,
  CircleAlert,
  CircleCheck,
  CircleDollarSign,
  CircleDot,
  CircleQuestionMark,
  CircleX,
  Clapperboard,
  ClipboardList,
  Clock,
  Cloud,
  Code,
  Coffee,
  Coins,
  Contact,
  Copy,
  Cpu,
  CreditCard,
  Crown,
  Database,
  Dog,
  Download,
  Droplet,
  Dumbbell,
  Ellipsis,
  ExternalLink,
  Eye,
  EyeOff,
  FaceSlightlySmiling,
  Factory,
  File,
  FileArchive,
  FileCode,
  FileSpreadsheet,
  FileText,
  Film,
  Fish,
  Flame,
  FlaskConical,
  Flower,
  Folder,
  Gem,
  Gift,
  GitBranch,
  Globe,
  GraduationCap,
  GripVertical,
  Hammer,
  Handshake,
  Hash,
  Headphones,
  Headset,
  Heart,
  HeartHandshake,
  Hospital,
  Hotel,
  House,
  IdCard,
  Image,
  Inbox,
  Info,
  Kanban,
  Key,
  Landmark,
  Laptop,
  Layers,
  LayoutGrid,
  Leaf,
  Library,
  Lightbulb,
  Link,
  ListChecks,
  ListFilter,
  ListTodo,
  LoaderCircle,
  Lock,
  Mail,
  Map,
  MapPin,
  Medal,
  Megaphone,
  MessageSquare,
  Mic,
  Microscope,
  Minus,
  Monitor,
  Moon,
  Mountain,
  Music,
  Newspaper,
  Notebook,
  Package,
  Palette,
  PanelLeftClose,
  PanelLeftOpen,
  PawPrint,
  Pen,
  Pencil,
  Phone,
  PiggyBank,
  Pin,
  PinOff,
  Pizza,
  Plane,
  Plug,
  Plus,
  Presentation,
  Printer,
  Puzzle,
  Radio,
  Receipt,
  RefreshCw,
  Rocket,
  Scale,
  School,
  Scissors,
  Search,
  Send,
  Server,
  Settings,
  ShieldCheck,
  Ship,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Snowflake,
  Sparkles,
  Sprout,
  SquareCheck,
  SquareFunction,
  Star,
  Stethoscope,
  Store,
  Sun,
  Tag,
  Target,
  Tent,
  Terminal,
  Ticket,
  Timer,
  TrainFront,
  Trash,
  TreePine,
  TrendingUp,
  TriangleAlert,
  Trophy,
  Truck,
  Tv,
  Type,
  Undo2,
  Upload,
  User,
  UserCheck,
  UserPlus,
  UserRound,
  Users,
  UsersRound,
  Utensils,
  Video,
  Wallet,
  Warehouse,
  WavesHorizontal,
  Wifi,
  Wrench,
  X,
  Zap,
} from 'lucide-react';

/** Lucide 1.49 icons by their lucide.dev name: the controls' own, one per attribute type, AI and help, and the curated object icons. */
export const icons = {
  activity: Activity,
  apple: Apple,
  archive: Archive,
  'arrow-down-wide-narrow': ArrowDownWideNarrow,
  'arrow-left': ArrowLeft,
  'arrow-left-right': ArrowLeftRight,
  'arrow-right': ArrowRight,
  'arrow-up-narrow-wide': ArrowUpNarrowWide,
  'arrow-up-right': ArrowUpRight,
  'at-sign': AtSign,
  atom: Atom,
  award: Award,
  baby: Baby,
  'badge-dollar-sign': BadgeDollarSign,
  'badge-percent': BadgePercent,
  banknote: Banknote,
  bell: Bell,
  bike: Bike,
  bird: Bird,
  blocks: Blocks,
  'book-open': BookOpen,
  bookmark: Bookmark,
  bot: Bot,
  box: Box,
  braces: Braces,
  brain: Brain,
  briefcase: Briefcase,
  'briefcase-business': BriefcaseBusiness,
  brush: Brush,
  bug: Bug,
  building: Building,
  'building-complex': BuildingComplex,
  cake: Cake,
  calendar: Calendar,
  'calendar-clock': CalendarClock,
  'calendar-days': CalendarDays,
  camera: Camera,
  car: Car,
  castle: Castle,
  cat: Cat,
  'chart-bar': ChartBar,
  'chart-line': ChartLine,
  'chart-pie': ChartPie,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  church: Church,
  'circle-alert': CircleAlert,
  'circle-check': CircleCheck,
  'circle-dollar-sign': CircleDollarSign,
  'circle-dot': CircleDot,
  'circle-question-mark': CircleQuestionMark,
  'circle-x': CircleX,
  clapperboard: Clapperboard,
  'clipboard-list': ClipboardList,
  clock: Clock,
  cloud: Cloud,
  code: Code,
  coffee: Coffee,
  coins: Coins,
  contact: Contact,
  copy: Copy,
  cpu: Cpu,
  'credit-card': CreditCard,
  crown: Crown,
  database: Database,
  dog: Dog,
  download: Download,
  droplet: Droplet,
  dumbbell: Dumbbell,
  ellipsis: Ellipsis,
  'external-link': ExternalLink,
  eye: Eye,
  'eye-off': EyeOff,
  'face-slightly-smiling': FaceSlightlySmiling,
  factory: Factory,
  file: File,
  'file-archive': FileArchive,
  'file-code': FileCode,
  'file-spreadsheet': FileSpreadsheet,
  'file-text': FileText,
  film: Film,
  fish: Fish,
  flame: Flame,
  'flask-conical': FlaskConical,
  flower: Flower,
  folder: Folder,
  gem: Gem,
  gift: Gift,
  'git-branch': GitBranch,
  globe: Globe,
  'graduation-cap': GraduationCap,
  'grip-vertical': GripVertical,
  hammer: Hammer,
  handshake: Handshake,
  hash: Hash,
  headphones: Headphones,
  headset: Headset,
  heart: Heart,
  'heart-handshake': HeartHandshake,
  hospital: Hospital,
  hotel: Hotel,
  house: House,
  'id-card': IdCard,
  image: Image,
  inbox: Inbox,
  info: Info,
  kanban: Kanban,
  key: Key,
  landmark: Landmark,
  laptop: Laptop,
  layers: Layers,
  'layout-grid': LayoutGrid,
  leaf: Leaf,
  library: Library,
  lightbulb: Lightbulb,
  link: Link,
  'list-checks': ListChecks,
  'list-filter': ListFilter,
  'list-todo': ListTodo,
  'loader-circle': LoaderCircle,
  lock: Lock,
  mail: Mail,
  map: Map,
  'map-pin': MapPin,
  medal: Medal,
  megaphone: Megaphone,
  'message-square': MessageSquare,
  mic: Mic,
  microscope: Microscope,
  minus: Minus,
  monitor: Monitor,
  moon: Moon,
  mountain: Mountain,
  music: Music,
  newspaper: Newspaper,
  notebook: Notebook,
  package: Package,
  palette: Palette,
  'panel-left-close': PanelLeftClose,
  'panel-left-open': PanelLeftOpen,
  'paw-print': PawPrint,
  pen: Pen,
  pencil: Pencil,
  phone: Phone,
  'piggy-bank': PiggyBank,
  pin: Pin,
  'pin-off': PinOff,
  pizza: Pizza,
  plane: Plane,
  plug: Plug,
  plus: Plus,
  presentation: Presentation,
  printer: Printer,
  puzzle: Puzzle,
  radio: Radio,
  receipt: Receipt,
  'refresh-cw': RefreshCw,
  rocket: Rocket,
  scale: Scale,
  school: School,
  scissors: Scissors,
  search: Search,
  send: Send,
  server: Server,
  settings: Settings,
  'shield-check': ShieldCheck,
  ship: Ship,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  smartphone: Smartphone,
  snowflake: Snowflake,
  sparkles: Sparkles,
  sprout: Sprout,
  'square-check': SquareCheck,
  'square-function': SquareFunction,
  star: Star,
  stethoscope: Stethoscope,
  store: Store,
  sun: Sun,
  tag: Tag,
  target: Target,
  tent: Tent,
  terminal: Terminal,
  ticket: Ticket,
  timer: Timer,
  'train-front': TrainFront,
  trash: Trash,
  'tree-pine': TreePine,
  'trending-up': TrendingUp,
  'triangle-alert': TriangleAlert,
  trophy: Trophy,
  truck: Truck,
  tv: Tv,
  type: Type,
  'undo-2': Undo2,
  upload: Upload,
  user: User,
  'user-check': UserCheck,
  'user-plus': UserPlus,
  'user-round': UserRound,
  users: Users,
  'users-round': UsersRound,
  utensils: Utensils,
  video: Video,
  wallet: Wallet,
  warehouse: Warehouse,
  'waves-horizontal': WavesHorizontal,
  wifi: Wifi,
  wrench: Wrench,
  x: X,
  zap: Zap,
} as const;

/** An icon in the registry, named exactly as lucide.dev lists it. */
export type IconName = keyof typeof icons;
