// The curated icons an object's tile may use: Lucide 1.49 names, picked so
// IconPicker offers a short, meaningful set and the registry in packages/ui
// can import each one (a test there checks the lists match). Lucide's dynamic
// loader isn't used: it would emit about 1,500 chunks.
import * as z from 'zod';

/** Every icon an object may pick, by its lucide.dev name, grouped as IconPicker shows them. */
export const OBJECT_ICONS = [
  // People
  'user',
  'users',
  'user-round',
  'users-round',
  'user-check',
  'user-plus',
  'contact',
  'baby',
  'graduation-cap',
  'briefcase',
  'briefcase-business',
  'id-card',
  'handshake',
  'heart-handshake',
  'crown',
  'smile',
  // Places and travel
  'building',
  'building-2',
  'factory',
  'store',
  'warehouse',
  'house',
  'hotel',
  'hospital',
  'school',
  'church',
  'landmark',
  'castle',
  'tent',
  'map',
  'map-pin',
  'globe',
  'plane',
  'car',
  'truck',
  'ship',
  'train-front',
  'bike',
  'rocket',
  'mountain',
  // Money and trade
  'banknote',
  'coins',
  'credit-card',
  'wallet',
  'piggy-bank',
  'receipt',
  'badge-dollar-sign',
  'badge-percent',
  'chart-line',
  'chart-bar',
  'chart-pie',
  'trending-up',
  'scale',
  'gem',
  'gift',
  'shopping-cart',
  'shopping-bag',
  'tag',
  'ticket',
  'package',
  // Work
  'folder',
  'file',
  'file-text',
  'clipboard-list',
  'notebook',
  'book-open',
  'library',
  'calendar',
  'calendar-days',
  'clock',
  'timer',
  'inbox',
  'mail',
  'send',
  'message-square',
  'phone',
  'headset',
  'megaphone',
  'presentation',
  'kanban',
  'list-checks',
  'list-todo',
  'target',
  'trophy',
  'medal',
  'award',
  'star',
  'bookmark',
  'pin',
  'lightbulb',
  'zap',
  'flame',
  'shield-check',
  'lock',
  'key',
  'bell',
  // Tools and tech
  'wrench',
  'hammer',
  'settings',
  'cpu',
  'server',
  'database',
  'laptop',
  'monitor',
  'smartphone',
  'printer',
  'wifi',
  'plug',
  'code',
  'terminal',
  'bug',
  'git-branch',
  'puzzle',
  'layers',
  'box',
  'blocks',
  'bot',
  'brain',
  'sparkles',
  'flask-conical',
  'microscope',
  'atom',
  // Media
  'camera',
  'image',
  'film',
  'video',
  'music',
  'headphones',
  'mic',
  'radio',
  'tv',
  'palette',
  'brush',
  'pen',
  'pencil',
  'scissors',
  'newspaper',
  'clapperboard',
  // Nature and food
  'leaf',
  'tree-pine',
  'flower',
  'sprout',
  'sun',
  'moon',
  'cloud',
  'snowflake',
  'droplet',
  'waves',
  'bird',
  'fish',
  'dog',
  'cat',
  'paw-print',
  'apple',
  'coffee',
  'utensils',
  'pizza',
  'cake',
  // Health
  'heart',
  'activity',
  'stethoscope',
  'dumbbell',
] as const;

/** One of the curated object icons. */
export const ObjectIcon = z.enum(OBJECT_ICONS, { error: 'Pick one of the object icons.' });
export type ObjectIcon = z.infer<typeof ObjectIcon>;
